-- PokemonData
--		name
--		catchrate
--		move
--		nature
--		type
--		status
--		item
--		map
-- RNGData
--		multspa
--		multspb
--		multspc
-- TableData
--		growth
--		attack
--		effort
--		misc
-- PickupData

PokemonData = {
	mons = {},
	move = {"", "Pound", "Karate Chop", "Double Slap", "Comet Punch", "Mega Punch", "Pay Day", "Fire Punch", "Ice Punch", "Thunder Punch", "Scratch", "Vise Grip", "Guillotine", "Razor Wind", "Swords Dance", "Cut", "Gust", "Wing Attack", "Whirlwind", "Fly", "Bind", "Slam", "Vine Whip", "Stomp", "Double Kick", "Mega Kick", "Jump Kick", "Rolling Kick", "Sand Attack", "Headbutt", "Horn Attack", "Fury Attack", "Horn Drill", "Tackle", "Body Slam", "Wrap", "Take Down", "Thrash", "Double-Edge", "Tail Whip", "Poison Sting", "Twineedle", "Pin Missile", "Leer", "Bite", "Growl", "Roar", "Sing", "Supersonic", "Sonic Boom", "Disable", "Acid", "Ember", "Flamethrower", "Mist", "Water Gun", "Hydro Pump", "Surf", "Ice Beam", "Blizzard", "Psybeam", "Bubble Beam", "Aurora Beam", "Hyper Beam", "Peck", "Drill Peck", "Submission", "Low Kick", "Counter", "Seismic Toss", "Strength", "Absorb", "Mega Drain", "Leech Seed", "Growth", "Razor Leaf", "Solar Beam", "Poison Powder", "Stun Spore", "Sleep Powder", "Petal Dance", "String Shot", "Dragon Rage", "Fire Spin", "Thunder Shock", "Thunderbolt", "Thunder Wave", "Thunder", "Rock Throw", "Earthquake", "Fissure", "Dig", "Toxic", "Confusion", "Psychic", "Hypnosis", "Meditate", "Agility", "Quick Attack", "Rage", "Teleport", "Night Shade", "Mimic", "Screech", "Double Team", "Recover", "Harden", "Minimize", "Smokescreen", "Confuse Ray", "Withdraw", "Defense Curl", "Barrier", "Light Screen", "Haze", "Reflect", "Focus Energy", "Bide", "Metronome", "Mirror Move", "Self-Destruct", "Egg Bomb", "Lick", "Smog", "Sludge", "Bone Club", "Fire Blast", "Waterfall", "Clamp", "Swift", "Skull Bash", "Spike Cannon", "Constrict", "Amnesia", "Kinesis", "Soft Boiled", "High Jump Kick", "Glare", "Dream Eater", "Poison Gas", "Barrage", "Leech Life", "Lovely Kiss", "Sky Attack", "Transform", "Bubble", "Dizzy Punch", "Spore", "Flash", "Psywave", "Splash", "Acid Armor", "Crabhammer", "Explosion", "Fury Swipes", "Bonemerang", "Rest", "Rock Slide", "Hyper Fang", "Sharpen", "Conversion", "Tri Attack", "Super Fang", "Slash", "Substitute", "Struggle", "Sketch", "Triple Kick", "Thief", "Spider Web", "Mind Reader", "Nightmare", "Flame Wheel", "Snore", "Curse", "Flail", "Conversion 2", "Aeroblast", "Cotton Spore", "Reversal", "Spite", "Powder Snow", "Protect", "Mach Punch", "Scary Face", "Feint Attack", "Sweet Kiss", "Belly Drum", "Sludge Bomb", "Mud-Slap", "Octazooka", "Spikes", "Zap Cannon", "Foresight", "Destiny Bond", "Perish Song", "Icy Wind", "Detect", "Bone Rush", "Lock-On", "Outrage", "Sandstorm", "Giga Drain", "Endure", "Charm", "Rollout", "False Swipe", "Swagger", "Milk Drink", "Spark", "Fury Cutter", "Steel Wing", "Mean Look", "Attract", "Sleep Talk", "Heal Bell", "Return", "Present", "Frustration", "Safeguard", "Pain Split", "Sacred Fire", "Magnitude", "Dynamic Punch", "Megahorn", "Dragon Breath", "Baton Pass", "Encore", "Pursuit", "Rapid Spin", "Sweet Scent", "Iron Tail", "Metal Claw", "Vital Throw", "Morning Sun", "Synthesis", "Moonlight", "Hidden Power", "Cross Chop", "Twister", "Rain Dance", "Sunny Day", "Crunch", "Mirror Coat", "Psych Up", "Extreme Speed", "Ancient Power", "Shadow Ball", "Future Sight", "Rock Smash", "Whirlpool", "Beat Up", "Fake Out", "Uproar", "Stockpile", "Spit Up", "Swallow", "Heat Wave", "Hail", "Torment", "Flatter", "Will-O-Wisp", "Memento", "Facade", "Focus Punch", "Smelling Salts", "Follow Me", "Nature Power", "Charge", "Taunt", "Helping Hand", "Trick", "Role Play", "Wish", "Assist", "Ingrain", "Superpower", "Magic Coat", "Recycle", "Revenge", "Brick Break", "Yawn", "Knock Off", "Endeavor", "Eruption", "Skill Swap", "Imprison", "Refresh", "Grudge", "Snatch", "Secret Power", "Dive", "Arm Thrust", "Camouflage", "Tail Glow", "Luster Purge", "Mist Ball", "Feather Dance", "Teeter Dance", "Blaze Kick", "Mud Sport", "Ice Ball", "Needle Arm", "Slack Off", "Hyper Voice", "Poison Fang", "Crush Claw", "Blast Burn", "Hydro Cannon", "Meteor Mash", "Astonish", "Weather Ball", "Aromatherapy", "Fake Tears", "Air Cutter", "Overheat", "Odor Sleuth", "Rock Tomb", "Silver Wind", "Metal Sound", "Grass Whistle", "Tickle", "Cosmic Power", "Water Spout", "Signal Beam", "Shadow Punch", "Extrasensory", "Sky Uppercut", "Sand Tomb", "Sheer Cold", "Muddy Water", "Bullet Seed", "Aerial Ace", "Icicle Spear", "Iron Defense", "Block", "Howl", "Dragon Claw", "Frenzy Plant", "Bulk Up", "Bounce", "Mud Shot", "Poison Tail", "Covet", "Volt Tackle", "Magical Leaf", "Water Sport", "Calm Mind", "Leaf Blade", "Dragon Dance", "Rock Blast", "Shock Wave", "Water Pulse", "Doom Desire", "Psycho Boost", "Roost", "Gravity", "Miracle Eye", "Wake-Up Slap", "Hammer Arm", "Gyro Ball", "Healing Wish", "Brine", "Natural Gift", "Feint", "Pluck", "Tailwind", "Acupressure", "Metal Burst", "U-turn", "Close Combat", "Payback", "Assurance", "Embargo", "Fling", "Psycho Shift", "Trump Card", "Heal Block", "Wring Out", "Power Trick", "Gastro Acid", "Lucky Chant", "Me First", "Copycat", "Power Swap", "Guard Swap", "Punishment", "Last Resort", "Worry Seed", "Sucker Punch", "Toxic Spikes", "Heart Swap", "Aqua Ring", "Magnet Rise", "Flare Blitz", "Force Palm", "Aura Sphere", "Rock Polish", "Poison Jab", "Dark Pulse", "Night Slash", "Aqua Tail", "Seed Bomb", "Air Slash", "X-Scissor", "Bug Buzz", "Dragon Pulse", "Dragon Rush", "Power Gem", "Drain Punch", "Vacuum Wave", "Focus Blast", "Energy Ball", "Brave Bird", "Earth Power", "Switcheroo", "Giga Impact", "Nasty Plot", "Bullet Punch", "Avalanche", "Ice Shard", "Shadow Claw", "Thunder Fang", "Ice Fang", "Fire Fang", "Shadow Sneak", "Mud Bomb", "Psycho Cut", "Zen Headbutt", "Mirror Shot", "Flash Cannon", "Rock Climb", "Defog", "Trick Room", "Draco Meteor", "Discharge", "Lava Plume", "Leaf Storm", "Power Whip", "Rock Wrecker", "Cross Poison", "Gunk Shot", "Iron Head", "Magnet Bomb", "Stone Edge", "Captivate", "Stealth Rock", "Grass Knot", "Chatter", "Judgment", "Bug Bite", "Charge Beam", "Wood Hammer", "Aqua Jet", "Attack Order", "Defend Order", "Heal Order", "Head Smash", "Double Hit", "Roar of Time", "Spacial Rend", "Lunar Dance", "Crush Grip", "Magma Storm", "Dark Void", "Seed Flare", "Ominous Wind", "Shadow Force", "Hone Claws", "Wide Guard", "Guard Split", "Power Split", "Wonder Room", "Psyshock", "Venoshock", "Autotomize", "Rage Powder", "Telekinesis", "Magic Room", "Smack Down", "Storm Throw", "Flame Burst", "Sludge Wave", "Quiver Dance", "Heavy Slam", "Synchronoise", "Electro Ball", "Soak", "Flame Charge", "Coil", "Low Sweep", "Acid Spray", "Foul Play", "Simple Beam", "Entrainment", "After You", "Round", "Echoed Voice", "Chip Away", "Clear Smog", "Stored Power", "Quick Guard", "Ally Switch", "Scald", "Shell Smash", "Heal Pulse", "Hex", "Sky Drop", "Shift Gear", "Circle Throw", "Incinerate", "Quash", "Acrobatics", "Reflect Type", "Retaliate", "Final Gambit", "Bestow", "Inferno", "Water Pledge", "Fire Pledge", "Grass Pledge", "Volt Switch", "Struggle Bug", "Bulldoze", "Frost Breath", "Dragon Tail", "Work Up", "Electroweb", "Wild Charge", "Drill Run", "Dual Chop", "Heart Stamp", "Horn Leech", "Sacred Sword", "Razor Shell", "Heat Crash", "Leaf Tornado", "Steamroller", "Cotton Guard", "Night Daze", "Psystrike", "Tail Slap", "Hurricane", "Head Charge", "Gear Grind", "Searing Shot", "Techno Blast", "Relic Song", "Secret Sword", "Glaciate", "Bolt Strike", "Blue Flare", "Fiery Dance", "Freeze Shock", "Ice Burn", "Snarl", "Icicle Crash", "V-create", "Fusion Flare", "Fusion Bolt", "Flying Press", "Mat Block", "Belch", "Rototiller", "Sticky Web", "Fell Stinger", "Phantom Force", "Trick-or-Treat", "Noble Roar", "Ion Deluge", "Parabolic Charge", "Forest's Curse", "Petal Blizzard", "Freeze-Dry", "Disarming Voice", "Parting Shot", "Topsy-Turvy", "Draining Kiss", "Crafty Shield", "Flower Shield", "Grassy Terrain", "Misty Terrain", "Electrify", "Play Rough", "Fairy Wind", "Moonblast", "Boomburst", "Fairy Lock", "King's Shield", "Play Nice", "Confide", "Diamond Storm", "Steam Eruption", "Hyperspace Hole", "Water Shuriken", "Mystical Fire", "Spiky Shield", "Aromatic Mist", "Eerie Impulse", "Venom Drench", "Powder", "Geomancy", "Magnetic Flux", "Happy Hour", "Electric Terrain", "Dazzling Gleam", "Celebrate", "Hold Hands", "Baby-Doll Eyes", "Nuzzle", "Hold Back", "Infestation", "Power-Up Punch", "Oblivion Wing", "Thousand Arrows", "Thousand Waves", "Land's Wrath", "Light of Ruin", "Origin Pulse", "Precipice Blades", "Dragon Ascent", "Hyperspace Fury", "Shore Up", "First Impression", "Baneful Bunker", "Spirit Shackle", "Darkest Lariat", "Sparkling Aria", "Ice Hammer", "Floral Healing", "High Horsepower", "Strength Sap", "Solar Blade", "Leafage", "Spotlight", "Toxic Thread", "Laser Focus", "Gear Up", "Throat Chop", "Pollen Puff", "Anchor Shot", "Psychic Terrain", "Lunge", "Fire Lash", "Power Trip", "Burn Up", "Speed Swap", "Smart Strike", "Purify", "Revelation Dance", "Core Enforcer", "Trop Kick", "Instruct", "Beak Blast", "Clanging Scales", "Dragon Hammer", "Brutal Swing", "Aurora Veil", "Shell Trap", "Fleur Cannon", "Psychic Fangs", "Stomping Tantrum", "Shadow Bone", "Accelerock", "Liquidation", "Prismatic Laser", "Spectral Thief", "Sunsteel Strike", "Moongeist Beam", "Tearful Look", "Zing Zap", "Nature's Madness", "Multi-Attack", "Mind Blown", "Plasma Fists", "Photon Geyser", "Zippy Zap", "Splishy Splash", "Floaty Fall", "Pika Papow", "Bouncy Bubble", "Buzzy Buzz", "Sizzly Slide", "Glitzy Glow", "Baddy Bad", "Sappy Seed", "Freezy Frost", "Sparkly Swirl", "Veevee Volley", "Double Iron Bash", "Dynamax Cannon", "Snipe Shot", "Jaw Lock", "Stuff Cheeks", "No Retreat", "Tar Shot", "Magic Powder", "Dragon Darts", "Teatime", "Octolock", "Bolt Beak", "Fishious Rend", "Court Change", "Clangorous Soul", "Body Press", "Decorate", "Drum Beating", "Snap Trap", "Pyro Ball", "Behemoth Blade", "Behemoth Bash", "Aura Wheel", "Breaking Swipe", "Branch Poke", "Overdrive", "Apple Acid", "Grav Apple", "Spirit Break", "Strange Steam", "Life Dew", "Obstruct", "False Surrender", "Meteor Assault", "Eternabeam", "Steel Beam", "Expanding Force", "Steel Roller", "Scale Shot", "Meteor Beam", "Shell Side Arm", "Misty Explosion", "Grassy Glide", "Rising Voltage", "Terrain Pulse", "Skitter Smack", "Burning Jealousy", "Lash Out", "Poltergeist", "Corrosive Gas", "Coaching", "Flip Turn", "Triple Axel", "Dual Wingbeat", "Scorching Sands", "Jungle Healing", "Wicked Blow", "Surging Strikes", "Thunder Cage", "Dragon Energy", "Freezing Glare", "Fiery Wrath", "Thunderous Kick", "Glacial Lance", "Astral Barrage", "Eerie Spell", "Dire Claw", "Psyshield Bash", "Power Shift", "Stone Axe", "Springtide Storm", "Mystical Power", "Raging Fury", "Wave Crash", "Chloroblast", "Mountain Gale", "Victory Dance", "Headlong Rush", "Barb Barrage", "Esper Wing", "Bitter Malice", "Shelter", "Triple Arrows", "Infernal Parade", "Ceaseless Edge", "Bleakwind Storm", "Wildbolt Storm", "Sandsear Storm", "Lunar Blessing", "Take Heart"
	},
	map = {
		"Littleroot Town", "Oldale Town", "Dewford Town", "Lavaridge Town", "Fallarbor Town", "Verdanturf Town",
		"Pacifidlog Town", "Petalburg City", "Slateport City", "Mauville City", "Rustboro City", 
		"Fortree City", "Lilycove City", "Mossdeep City", "Sootopolis City", "Ever Grande City", "Route 101", 
		"Route 102", "Route 103", "Route 104", "Route 105", "Route 106", "Route 107", "Route 108", "Route 109",
		"Route 110", "Route 111", "Route 112", "Route 113", "Route 114", "Route 115", "Route 116", 
		"Route 117", "Route 118", "Route 119", "Route 120", "Route 121", "Route 122", "Route 123", "Route 124",
		"Route 125", "Route 126", "Route 127", "Route 128", "Route 129", "Route 130", "Route 131", 
		"Route 132", "Route 133", "Route 134", "Underwater�(Route 124)", "Underwater�(Route 126)", 
		"Underwater�(Route 127)", "Underwater�(Route 128)", "Underwater�(Sootopolis City)", "Granite Cave", 
		"Mt. Chimney", "Safari Zone", "Battle Frontier", "Petalburg Woods", "Rusturf Tunnel", 
		"Abandoned Ship", "New Mauville", "Meteor Falls", "Meteor Falls", "Mt. Pyre", "Hideout", "Shoal Cave",
		"Seafloor Cavern", "Underwater�(Seafloor Cavern)", "Victory Road", "Mirage Island", "Cave of Origin",
		"Southern Island", "Fiery Path", "Fiery Path", "Jagged Pass", "Jagged Pass", "Sealed Chamber",
		"Underwater�(Route 134)", "Scorched Slab", "Island Cave", "Desert Ruins", "Ancient Tomb", 
		"Inside of Truck", "Sky Pillar", "Secret Base", "Ferry", "Pallet Town", "Viridian City", "Pewter City",
		"Cerulean City", "Lavender Town", "Vermilion City", "Celadon City", "Fuchsia City", "Cinnabar Island",
		"Indigo Plateau", "Saffron City", "Route 4�(Pok�mon Center)", "Route 10�(Pok�mon Center)", 
		"Route 1", "Route 2", "Route 3", "Route 4", "Route 5", "Route 6", "Route 7", "Route 8", "Route 9", 
		"Route 10", "Route 11", "Route 12", "Route 13", "Route 14", "Route 15", "Route 16", "Route 17", 
		"Route 18", "Route 19", "Route 20", "Route 21", "Route 22", "Route 23", "Route 24", "Route 25", 
		"Viridian Forest", "Mt. Moon", "S.S. Anne", "Underground Path�(Routes�5-6)",
		"Underground Path�(Routes�7-8)", "Diglett's Cave", "Victory Road", "Rocket Hideout", "Silph Co.",
		"Pok�mon Mansion", "Safari Zone", "Pok�mon League", "Rock Tunnel", "Seafoam Islands", "Pok�mon Tower", 
		"Cerulean Cave", "Power Plant", "One Island", "Two Island", "Three Island", "Four Island", "Five Island",
		"Seven Island", "Six Island", "Kindle Road", "Treasure Beach", "Cape Brink", "Bond Bridge", 
		"Three Isle Port", "Sevii Isle 6", "Sevii Isle 7", "Sevii Isle 8", "Sevii Isle 9", "Resort Gorgeous", 
		"Water Labyrinth", "Five Isle Meadow", "Memorial Pillar", "Outcast Island", "Green Path", "Water Path",
		"Ruin Valley", "Trainer Tower", "Canyon Entrance", "Sevault Canyon", "Tanoby Ruins",
		"Sevii Isle 22", "Sevii Isle 23", "Sevii Isle 24", "Navel Rock", "Mt. Ember", "Berry Forest", "Icefall Cave",
		"Rocket Warehouse", "Trainer Tower", "Dotted Hole", "Lost Cave", "Pattern Bush",
		"Altering Cave", "Tanoby Chambers", "Three Isle Path", "Tanoby Key", "Birth Island", "Monean Chamber",
		"Liptoo Chamber", "Weepth Chamber", "Dilford Chamber", "Scufib Chamber", "Rixy Chamber", "Viapois Chamber", 
		"Ember Spa", "Celadon Dept", "Aqua Hideout", "Magma Hideout", "Mirage Tower", "Birth Island", 
		"Faraway Island", "Artisan Cave", "Marine Cave", "Underwater�(Marine Cave)", "Terra Cave", 
		"Underwater�(Route 105)", "Underwater�(Route 125)", "Underwater�(Route 129)", "Desert Underpass", 
		"Altering Cave", "Navel Rock", "Trainer Hill", "none", "none", "none", "none", "none", "none", 
		"none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", 
		"none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", 
		"none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "In-game trade", "Fateful encounter"
	},
	encounterRoutes = {"Starter", "Littleroot Town", "Route 101", "Oldale Town", "Route 103", "Route 102", "Petalburg City", "Route 104",
	"Dewford Town", "Route 107", "Route 106", "Granite Cave", "Route 109", "Slateport City", "Route 110", "Petalburg Woods",
	"Rustboro City", "Route 115", "Route 116", "Rusturf Tunnel", "Verdanturf Town", "Route 117", "Mauville City", "Route 111",
	"Route 118", "Altering Cave", "Mirage Tower", "Route 113", "Fallarbor Town", "Desert Underpass", "Route 114", "Meteor Falls",
	"Route 112", "Fiery Path", "Mt. Chimney", "Jagged Pass", "Lavaridge Town", "Route 134", "New Mauville", "Route 105", "Route 108",
	"Abandoned Ship", "Route 119", "Route 120", "Fortree City", "Scorched Slab", "Route 121", "Safari Zone", "Lilycove City",
	"Route 122", "Route 123", "Mt. Pyre", "Magma Hideout", "Aqua Hideout", "Route 124", "Mossdeep City", "Route 125", "Shoal Cave",
	"Route 127", "Route 126", "Sootopolis City", "Route 128", "Route 129", "Ever Grande City", "Seafloor Cavern", "Cave of Origin",
	"Route 130", "Route 131", "Pacifidlog Town", "Route 132", "Route 133", "Sky Pillar", "Victory Road"
	},

	nature = {
		"Hardy", "Lonely", "Brave", "Adamant", "Naughty",
		"Bold", "Docile", "Relaxed", "Impish", "Lax",
		"Timid", "Hasty", "Serious", "Jolly", "Naive",
		"Modest", "Mild", "Quiet", "Bashful", "Rash",
		"Calm", "Gentle", "Sassy", "Careful", "Quirky"
	},
	type = { "Normal",
		"Fighting","Flying","Poison","Ground",
		"Rock","Bug","Ghost","Steel", "Fairy",
		"Fire","Water","Grass","Electric",
		"Psychic","Ice","Dragon","Dark","Fairy"
	},
	typeColor = { 0xFF9FA19F,
		0xFFFF8000, 0xFF81B9EF, 0xFF9141CB, 0xFF915121,
		0xFFAFA981, 0xFF91A119, 0xFF704170, 0xFF60A1B8, 0xFFEF70EF,
		0xFFE62829, 0xFF2980EF, 0xFF3FA129, 0xFFFAC000, 
		0xFFEF4179, 0xFF3DCEF3, 0xFF5060E1, 0xFF624D4E 
	},
	status = {
		"None","Sleep","Poison","Burn","Freeze",
		"Paralysis","Bad Poison"
	},
	item = {"Poke Ball", "Great Ball", "Ultra Ball", "Master Ball", "Premier Ball", "Heal Ball", "Net Ball", "Nest Ball", "Dive Ball", "Dusk Ball", "Timer Ball", "Quick Ball", "Repeat Ball", "Luxury Ball", "Level Ball", "Lure Ball", "Moon Ball", "Friend Ball", "Love Ball", "Fast Ball", "Heavy Ball", "Dream Ball", "Safari Ball", "Sport Ball", "Park Ball", "Beast Ball", "Cherish Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Berry Juice", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Bottle Cap", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Rare Bone", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Helix Fossil", "Dome Fossil", "Old Amber", "Root Fossil", "Claw Fossil", "Armor Fossil", "Skull Fossil", "Cover Fossil", "Plume Fossil", "Jaw Fossil", "Sail Fossil", "Fossilized Bird", "Fossilized Fish", "Fossilized Drake", "Fossilized Dino", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Mail", "Mail", "Mail", "Mail", "Mail", "Mail", "Mail", "Mail", "Mail", "Mail", "Mail", "Mail", "Fire Stone", "Water Stone", "Thunder Stone", "Leaf Stone", "Ice Stone", "Sun Stone", "Moon Stone", "Shiny Stone", "Dusk Stone", "Dawn Stone", "Sweet Apple", "Tart Apple", "Cracked Pot", "Chipped Pot", "Galarica Cuff", "Galarica Wreath", "Dragon Scale", "Up-Grade", "Protector", "Electirizer", "Magmarizer", "Dubious Disc", "Reaper Cloth", "Prism Scale", "Whipped Dream", "Sachet", "Oval Stone", "Strawberry Sweet", "Love Sweet", "Berry Sweet", "Clover Sweet", "Flower Sweet", "Star Sweet", "Ribbon Sweet", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Flame Plate", "Splash Plate", "Zap Plate", "Meadow Plate", "Icicle Plate", "Fist Plate", "Toxic Plate", "Earth Plate", "Sky Plate", "Mind Plate", "Insect Plate", "Stone Plate", "Spooky Plate", "Draco Plate", "Dread Plate", "Iron Plate", "Pixie Plate", "Douse Drive", "Shock Drive", "Burn Drive", "Chill Drive", "Fire Memory", "Water Memory", "Electric Memory", "Grass Memory", "Ice Memory", "Fighting Memory", "Poison Memory", "Ground Memory", "Flying Memory", "Psychic Memory", "Bug Memory", "Rock Memory", "Ghost Memory", "Dragon Memory", "Dark Memory", "Steel Memory", "Fairy Memory", "Rusted Sword", "Rusted Shield", "Red Orb", "Blue Orb", "Venusaurite 84 Venusaur", "Charizardite X", "Charizardite Y", "Blastoisinite", "Beedrillite", "Pidgeotite", "Alakazite", "Slowbronite", "Gengarite", "Kangaskhanite", "Pinsirite", "Gyaradosite", "Aerodactylite", "Mewtwonite X", "Mewtwonite Y", "Ampharosite", "Steelixite", "Scizorite", "Heracronite", "Houndoominite", "Tyranitarite", "Sceptilite", "Blazikenite", "Swampertite", "Gardevoirite", "Sablenite", "Mawilite", "Aggronite", "Medichamite", "Manectite", "Sharpedonite", "Cameruptite", "Altarianite", "Banettite", "Absolite", "Glalitite", "Salamencite", "Metagrossite", "Latiasite", "Latiosite", "Lopunnite", "Garchompite", "Lucarionite", "Abomasite", "Galladite", "Audinite", "Diancite", "Normal Gem", "Fire Gem", "Water Gem", "Electric Gem", "Grass Gem", "Ice Gem", "Fighting Gem", "Poison Gem", "Ground Gem", "Flying Gem", "Psychic Gem", "Bug Gem", "Rock Gem", "Ghost Gem", "Dragon Gem", "Dark Gem", "Steel Gem", "Fairy Gem", "Normalium Z", "Firium Z", "Waterium Z", "Electrium Z", "Grassium Z", "Icium Z", "Fightinium Z", "Poisonium Z", "Groundium Z", "Flyinium Z", "Psychium Z", "Buginium Z", "Rockium Z", "Ghostium Z", "Dragonium Z", "Darkinium Z", "Steelium Z", "Fairium Z", "Pikanium Z", "Eevium Z", "Snorlium Z", "Mewnium Z", "Decidium Z", "Incinium Z", "Primarium Z", "Lycanium Z", "Mimikium Z", "Kommonium Z", "Tapunium Z", "Solganium Z", "Lunalium Z", "Marshadium Z", "Aloraichium Z", "Pikashunium Z", "Ultranecrozium Z", "Light Ball", "Leek", "Thick Club", "Lucky Punch", "Metal Powder", "Quick Powder", "Deep Sea Scale", "Deep Sea Tooth", "Soul Dew", "Adamant Orb", "Lustrous Orb", "Griseous Orb", "Sea Incense", "Lax Incense", "Odd Incense", "Rock Incense", "Full Incense", "Wave Incense", "Rose Incense", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Macho Brace", "Power Weight", "Power Bracer", "Power Belt", "Power Lens", "Power Band", "Power Anklet", "Silk Scarf", "Charcoal", "Mystic Water", "Magnet", "Miracle Seed", "Never-Melt Ice", "Black Belt", "Poison Barb", "Soft Sand", "Sharp Beak", "Twisted Spoon", "Silver Powder", "Hard Stone", "Spell Tag", "Dragon Fang", "Black Glasses", "Metal Coat", "Choice Band", "Choice Specs", "Choice Scarf", "Flame Orb", "Toxic Orb", "Damp Rock", "Heat Rock", "Smooth Rock", "Icy Rock", "Electric Seed", "Psychic Seed", "Misty Seed", "Grassy Seed", "Absorb Bulb", "Cell Battery", "Luminous Moss", "Snowball", "Bright Powder", "White Herb", "Poke Ball", "Quick Claw", "Poke Ball", "Mental Herb", "King's Rock", "Poke Ball", "Poke Ball", "Poke Ball", "Focus Band", "Poke Ball", "Scope Lens", "Leftovers", "Shell Bell", "Wide Lens", "Muscle Band", "Wise Glasses", "Expert Belt", "Light Clay", "Life Orb", "Power Herb", "Focus Sash", "Zoom Lens", "Metronome", "Iron Ball", "Lagging Tail", "Destiny Knot", "Black Sludge", "Grip Claw", "Sticky Barb", "Shed Shell", "Big Root", "Razor Claw", "Razor Fang", "Eviolite", "Float Stone", "Rocky Helmet", "Air Balloon", "Red Card", "Ring Target", "Binding Band", "Eject Button", "Weakness Policy", "Assault Vest", "Safety Goggles", "Adrenaline Orb", "Terrain Extender", "Protective Pads", "Throat Spray", "Eject Pack", "Heavy-Duty Boots", "Blunder Policy", "Room Service", "Utility Umbrella", "Cheri Berry", "Chesto Berry", "Pecha Berry", "Rawst Berry", "Aspear Berry", "Leppa Berry", "Oran Berry", "Persim Berry", "Lum Berry", "Sitrus Berry", "Figy Berry", "Wiki Berry", "Mago Berry", "Aguav Berry", "Iapapa Berry", "Razz Berry", "Bluk Berry", "Nanab Berry", "Wepear Berry", "Pinap Berry", "Pomeg Berry", "Kelpsy Berry", "Qualot Berry", "Hondew Berry", "Grepa Berry", "Tamato Berry", "Cornn Berry", "Magost Berry", "Rabuta Berry", "Nomel Berry", "Spelon Berry", "Pamtre Berry", "Watmel Berry", "Durin Berry", "Belue Berry", "Chilan Berry", "Occa Berry", "Passho Berry", "Wacan Berry", "Rindo Berry", "Yache Berry", "Chople Berry", "Kebia Berry", "Shuca Berry", "Coba Berry", "Payapa Berry", "Tanga Berry", "Charti Berry", "Kasib Berry", "Haban Berry", "Colbur Berry", "Babiri Berry", "Roseli Berry", "Liechi Berry", "Ganlon Berry", "Salac Berry", "Petaya Berry", "Apicot Berry", "Lansat Berry", "Starf Berry", "Enigma Berry", "Micle Berry", "Custap Berry", "Jaboca Berry", "Rowap Berry", "Kee Berry", "Maranga Berry", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", "Poke Ball", 
	},
	blankMon = {
		personality = 0,
		otId = 0,
		tid = 0,
		sid = 0,
		isShiny = false,
		nickname = "",
		language =0,
		isBadEgg = false,
		hasSpecies = true,
		isEgg = false,
		otName = "",
		markings = 0,
		pokemonID = 0,
		heldItem = 0,
		experience = 0,
		ppBonuses = 0,
		friendship = 0,
		nature = 0,
		moves = {},
		pp = {},
		hpEV = 0,
		attackEV = 0,
		defenseEV = 0,
		speedEV = 0,
		spAttackEV = 0,
		spDefenseEV = 0,
		cool = 0,
		beauty = 0,
		cute = 0,
		smart = 0,
		tough = 0,
		sheen = 0,
		pokerus = 0,
		metLocation = 0,
		metLevel = 0,
		metGame = 0,
		pokeball = 0,
		otGender = 0,
		hpIV = 0,
		attackIV = 0,
		defenseIV = 0,
		speedIV = 0,
		spAttackIV = 0,
		spDefenseIV = 0,
		coolRibbon = 0,
		beautyRibbon = 0,
		cuteRibbon = 0,
		smartRibbon = 0,
		toughRibbon = 0,
		championRibbon = 0,
		winningRibbon = 0,
		victoryRibbon = 0,
		artistRibbon = 0,
		effortRibbon = 0,
		marineRibbon = 0,
		landRibbon = 0,
		skyRibbon = 0,
		countryRibbon = 0,
		nationalRibbon = 0,
		earthRibbon = 0,
		worldRibbon = 0,
		altAbility = 0,
		gender = "Unknown",
		status = "",
		sleepTurns = 0,
		level = 0,
		mail = 0,
		hp = 0,
		maxHP = 0,
		attack = 0,
		defense = 0,
		speed = 0,
		spAttack = 0,
		spDefense = 0,
		isEnemy = false
	},
	variants = {"Venusaur-Mega",
"Charizard-Mega-X",
"Charizard-Mega-Y",
"Blastoise-Mega",
"Beedrill-Mega",
"Pidgeot-Mega",
"Alakazam-Mega",
"Slowbro-Mega",
"Gengar-Mega",
"Kangaskhan-Mega",
"Pinsir-Mega",
"Gyarados-Mega",
"Aerodactyl-Mega",
"Mewtwo-Mega-X",
"Mewtwo-Mega-Y",
"Ampharos-Mega",
"Steelix-Mega",
"Scizor-Mega",
"Heracross-Mega",
"Houndoom-Mega",
"Tyranitar-Mega",
"Sceptile-Mega",
"Blaziken-Mega",
"Swampert-Mega",
"Gardevoir-Mega",
"Sableye-Mega",
"Mawile-Mega",
"Aggron-Mega",
"Medicham-Mega",
"Manectric-Mega",
"Sharpedo-Mega",
"Camerupt-Mega",
"Altaria-Mega",
"Banette-Mega",
"Absol-Mega",
"Glalie-Mega",
"Salamence-Mega",
"Metagross-Mega",
"Latias-Mega",
"Latios-Mega",
"Lopunny-Mega",
"Garchomp-Mega",
"Lucario-Mega",
"Abomasnow-Mega",
"Gallade-Mega",
"Audino-Mega",
"Diancie-Mega",
"Rayquaza-Mega",
"Kyogre-Primal",
"Groudon-Primal",
"Rattata-Alola",
"Raticate-Alola",
"Raichu-Alola",
"Sandshrew-Alola",
"Sandslash-Alola",
"Vulpix-Alola",
"Ninetales-Alola",
"Diglett-Alola",
"Dugtrio-Alola",
"Meowth-Alola",
"Persian-Alola",
"Geodude-Alola",
"Graveler-Alola",
"Golem-Alola",
"Grimer-Alola",
"Muk-Alola",
"Exeggutor-Alola",
"Marowak-Alola",
"Meowth-Galar",
"Ponyta-Galar",
"Rapidash-Galar",
"Slowpoke-Galar",
"Slowbro-Galar",
"Farfetch’d-Galar",
"Weezing-Galar",
"Mr. Mime-Galar",
"Articuno-Galar",
"Zapdos-Galar",
"Moltres-Galar",
"Slowking-Galar",
"Corsola-Galar",
"Zigzagoon-Galar",
"Linoone-Galar",
"Darumaka-Galar",
"Darmanitan-Galar",
"Yamask-Galar",
"Stunfisk-Galar",
"Growlithe-Hisui",
"Arcanine-Hisui",
"Voltorb-Hisui",
"Electrode-Hisui",
"Typhlosion-Hisui",
"Qwilfish-Hisui",
"Sneasel-Hisui",
"Samurott-Hisui",
"Lilligant-Hisui",
"Zorua-Hisui",
"Zoroark-Hisui",
"Braviary-Hisui",
"Sliggoo-Hisui",
"Goodra-Hisui",
"Avalugg-Hisui",
"Decidueye-Hisui",
"Pikachu-Cosplay",
"Pikachu-Rock-Star",
"Pikachu-Belle",
"Pikachu-Pop-Star",
"Pikachu-PhD",
"Pikachu-Libre",
"Pikachu-Original",
"Pikachu-Hoenn",
"Pikachu-Sinnoh",
"Pikachu-Unova",
"Pikachu-Kalos",
"Pikachu-Alola",
"Pikachu-Partner",
"Pikachu-World",
"Pichu-Spiky-eared",
"Unown-B",
"Unown-C",
"Unown-D",
"Unown-E",
"Unown-F",
"Unown-G",
"Unown-H",
"Unown-I",
"Unown-J",
"Unown-K",
"Unown-L",
"Unown-M",
"Unown-N",
"Unown-O",
"Unown-P",
"Unown-Q",
"Unown-R",
"Unown-S",
"Unown-T",
"Unown-U",
"Unown-V",
"Unown-W",
"Unown-X",
"Unown-Y",
"Unown-Z",
"Unown-!",
"Unown-?",
"Castform-Sunny",
"Castform-Rainy",
"Castform-Snowy",
"Deoxys-Attack",
"Deoxys-Defense",
"Deoxys-Speed",
"Burmy-Sandy",
"Burmy-Trash",
"Wormadam-Sandy",
"Wormadam-Trash",
"Cherrim-Sunshine",
"Shellos-East",
"Gastrodon-East",
"Rotom-Heat",
"Rotom-Wash",
"Rotom-Frost",
"Rotom-Fan",
"Rotom-Mow",
"Dialga-Origin",
"Palkia-Origin",
"Giratina-Origin",
"Shaymin-Sky",
"Arceus-Fighting",
"Arceus-Flying",
"Arceus-Poison",
"Arceus-Ground",
"Arceus-Rock",
"Arceus-Bug",
"Arceus-Ghost",
"Arceus-Steel",
"Arceus-Fire",
"Arceus-Water",
"Arceus-Grass",
"Arceus-Electric",
"Arceus-Psychic",
"Arceus-Ice",
"Arceus-Dragon",
"Arceus-Dark",
"Arceus-Fairy",
"Basculin-Blue-Striped",
"Basculin-White-Striped",
"Darmanitan-Zen",
"Darmanitan-Galar-Zen",
"Deerling-Winter",
"Deerling-Autumn",
"Deerling-Summer",
"Sawsbuck-Winter",
"Sawsbuck-Autumn",
"Sawsbuck-Summer",
"Tornadus-Therian",
"Thundurus-Therian",
"Landorus-Therian",
"Enamorus-Therian",
"Kyurem-White",
"Kyurem-Black",
"Keldeo-Resolute",
"Meloetta-Pirouette",
"Genesect-Douse",
"Genesect-Shock",
"Genesect-Burn",
"Genesect-Chill",
"Greninja",
"Greninja-Ash",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Flabébé",
"Flabébé",
"Flabébé",
"Flabébé",
"Floette",
"Floette",
"Floette",
"Floette",
"Floette-Eternal",
"Florges",
"Florges",
"Florges",
"Florges",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Furfrou",
"Meowstic-F",
"Aegislash-Blade",
"Pumpkaboo-Small",
"Pumpkaboo-Large",
"Pumpkaboo-Super",
"Gourgeist-Small",
"Gourgeist-Large",
"Gourgeist-Super",
"Xerneas",
"Zygarde-10",
"Zygarde-10",
"Zygarde",
"Zygarde-Complete",
"Hoopa-Unbound",
"Oricorio-Pom-Pom",
"Oricorio-Pa'u ",
"Oricorio-Sensu",
"Rockruff",
"Lycanroc-Midnight",
"Lycanroc-Dusk",
"Wishiwashi-School",
"Silvally-Fighting",
"Silvally-Flying",
"Silvally-Poison",
"Silvally-Ground",
"Silvally-Rock",
"Silvally-Bug",
"Silvally-Ghost",
"Silvally-Steel",
"Silvally-Fire",
"Silvally-Water",
"Silvally-Grass",
"Silvally-Electric",
"Silvally-Psychic",
"Silvally-Ice",
"Silvally-Dragon",
"Silvally-Dark",
"Silvally-Fairy",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Mimikyu-Busted",
"Necrozma-Dusk-Mane",
"Necrozma-Dawn-Wings",
"Necrozma-Ultra",
"Magearna-Original",
"Cramorant-Gulping",
"Cramorant-Gorging",
"Toxtricity-Low-Key",
"Sinistea-Antique",
"Polteageist-Antique",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Alcremie",
"Eiscue-Noice",
"Indeedee-F",
"Morpeko-Hangry",
"Zacian-Crowned",
"Zamazenta-Crowned",
"Eternatus-Eternamax",
"Urshifu-Rapid-Strike",
"Zarude-Dada",
"Calyrex-Ice",
"Calyrex-Shadow"
},
}
CharData ={
	charmap = { [0]=
	" ", "À", "Á", "Â", "Ç", "È", "É", "Ê", "Ë", "Ì", "こ", "Î", "Ï", "Ò", "Ó", "Ô",
	"Œ", "Ù", "Ú", "Û", "Ñ", "ß", "à", "á", "ね", "ç", "è", "é", "ê", "ë", "ì", "ま",
	"î", "ï", "ò", "ó", "ô", "œ", "ù", "ú", "û", "ñ", "º", "ª", "�", "&", "+", "あ",
	"ぃ", "ぅ", "ぇ", "ぉ", "v", "=", "ょ", "が", "ぎ", "ぐ", "げ", "ご", "ざ", "じ", "ず", "ぜ",
	"ぞ", "だ", "ぢ", "づ", "で", "ど", "ば", "び", "ぶ", "べ", "ぼ", "ぱ", "ぴ", "ぷ", "ぺ", "ぽ",
	"っ", "¿", "¡", "P\u{200d}k", "M\u{200d}n", "P\u{200d}o", "K\u{200d}é", "�", "�", "�", "Í", "%", "(", ")", "セ", "ソ",
	"タ", "チ", "ツ", "テ", "ト", "ナ", "ニ", "ヌ", "â", "ノ", "ハ", "ヒ", "フ", "ヘ", "ホ", "í",
	"ミ", "ム", "メ", "モ", "ヤ", "ユ", "ヨ", "ラ", "リ", "⬆", "⬇", "⬅", "➡", "ヲ", "ン", "ァ",
	"ィ", "ゥ", "ェ", "ォ", "ャ", "ュ", "ョ", "ガ", "ギ", "グ", "ゲ", "ゴ", "ザ", "ジ", "ズ", "ゼ",
	"ゾ", "ダ", "ヂ", "ヅ", "デ", "ド", "バ", "ビ", "ブ", "ベ", "ボ", "パ", "ピ", "プ", "ペ", "ポ",
	"ッ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "!", "?", ".", "-", "・",
	"…", "“", "”", "‘", "’", "♂", "♀", "$", ",", "×", "/", "A", "B", "C", "D", "E",
	"F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U",
	"V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
	"l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "▶",
	":", "Ä", "Ö", "Ü", "ä", "ö", "ü", "⬆", "⬇", "⬅", "�", "�", "�", "�", "�", ""
}
}
RNGData = {
	multspa = {
		0x41C64E6D, 0xC2A29A69, 0xEE067F11, 0xCFDDDF21,
		0x5F748241, 0x8B2E1481, 0x76006901, 0x1711D201,
		0xBE67A401, 0xDDDF4801, 0x3FFE9001, 0x90FD2001,
		0x65FA4001, 0xDBF48001, 0xF7E90001, 0xEFD20001,
		0xDFA40001, 0xBF480001, 0x7E900001, 0xFD200001,
		0xFA400001, 0xF4800001, 0xE9000001, 0xD2000001,
		0xA4000001, 0x48000001, 0x90000001, 0x20000001,
		0x40000001, 0x80000001, 0x00000001, 0x00000001
	},
	multspb={
		0x00006073, 0xE97E7B6A, 0x31B0DDE4, 0x67DBB608,
		0xCBA72510, 0x1D29AE20, 0xBA84EC40, 0x79F01880,
		0x08793100, 0x6B566200, 0x803CC400, 0xA6B98800,
		0xE6731000, 0x30E62000, 0xF1CC4000, 0x23988000,
		0x47310000, 0x8E620000, 0x1CC40000, 0x39880000,
		0x73100000, 0xE6200000, 0xCC400000, 0x98800000,
		0x31000000, 0x62000000, 0xC4000000, 0x88000000,
		0x10000000, 0x20000000, 0x40000000, 0x80000000
	},
	multspc={
		0x00003039, 0xD3DC167E, 0xD6651C2C, 0xCD1DCF18,
		0x65136930, 0x642B7E60, 0x1935ACC0, 0xB6461980,
		0x1EF73300, 0x1F9A6600, 0x85E4CC00, 0x26899800,
		0xB8133000, 0x1C266000, 0xE84CC000, 0x90998000,
		0x21330000, 0x42660000, 0x84CC0000, 0x09980000,
		0x13300000, 0x26600000, 0x4CC00000, 0x99800000,
		0x33000000, 0x66000000, 0xCC000000, 0x98000000,
		0x30000000, 0x60000000, 0xC0000000, 0x80000000
	}
}

TableData = {
	growth = {1,1,1,1,1,1, 2,2,3,4,3,4, 2,2,3,4,3,4, 2,2,3,4,3,4},
	attack = {2,2,3,4,3,4, 1,1,1,1,1,1, 3,4,2,2,4,3, 3,4,2,2,4,3},
	effort = {3,4,2,2,4,3, 3,4,2,2,4,3, 1,1,1,1,1,1, 4,3,4,3,2,2},
	misc   = {4,3,4,3,2,2, 4,3,4,3,2,2, 4,3,4,3,2,2, 1,1,1,1,1,1}
}

MoveData = {
	targets = {
		[0x00] = "Selected Target",
		[0x01] = "Depends on the attack",
		[0x02] = "Not in use",
		[0x04] = "Random Foe",
		[0x08] = "Both foes",
		[0x10] = "User",
		[0x20] = "Both foes and partner",
		[0x40] = "opponent field",
		[0x80] = "Unknown"
	},
	flagOrder = {
		0x80, 0x40, 0x20, 0x10, 0x8, 0x4, 0x2, 0x1
	}
}